language = "C"
ext = "c"

environment = [
  { name = "main.c", install = "sudo apt update && sudo apt -y upgrade && sudo apt install -y build-essential", build = "gcc -Wall -O3 $FILE",  run = "./$FILE.out", version = "gcc --version" }
]
