language = "Crystal"
ext = "cr"

enviroment = [
  { name = "main.cr", install = "curl -fsSL https://crystal-lang.org/install.sh | sudo bash", build = "crystal build $FILE --release --no-debug", run = "./$FILE", version = "crystal -v" }
]
