language = "JavaScript"
ext = "mjs"

enviroment = [
  { name = "main.bun.mjs", install = "curl https://bun.sh/install | bash && echo 'export PATH=$HOME/.bun/bin:$PATH' >> $PROFILE", run = "bun $FILE$EXTENSION", version = "bun -v" },
  { name = "main.deno.mjs", install = "curl -fsSL https://deno.land/install.sh | bash && echo 'export PATH=$HOME/.deno/bin:$PATH' >> $PROFILE", run = "deno run --allow-net $FILE$EXTENSION", version = "deno --version" },
  { name = "main.node.mjs", install = "curl -sL https://deb.nodesource.com/setup_current.x | bash", run = "node $FILE$EXTENSION", version = "node --version" }
]