language = "JavaScript"
ext = "mjs"

environment = [
  { name = "main.bun.mjs", runtime = "bun", install = "curl https://bun.sh/install | bash && echo 'export PATH=$HOME/.bun/bin:$PATH' >> $PROFILE", run = "bun $FILE$EXTENSION", version = "bun -v" },
  { name = "main.deno.mjs", runtime = "deno", install = "curl -fsSL https://deno.land/install.sh | bash && echo 'export PATH=$HOME/.deno/bin:$PATH' >> $PROFILE", run = "deno run --allow-net --allow-write --allow-read --allow-hrtime --unstable $FILE$EXTENSION", version = "deno --version" },
  { name = "flash.deno.mjs", extend = "main.deno.mjs", type = "flash (new Deno.serve)" },
  { name = "main.node.mjs", runtime = "node", install = "curl -sL https://deb.nodesource.com/setup_current.x | bash && sudo apt install nodejs", run = "node $FILE$EXTENSION", version = "node --version" }
]
