language = "Python"
ext = "py"

environment = [
  { name = "main.py", install = "sudo apt update && sudo apt -y upgrade && sudo apt-get install -y python3-pip && pip install nanoid && pip install requests", run = "python3 $FILE$EXTENSION", version = "python3 -V" }
]
