name: Run benchmarks

on:
  schedule:
    - cron: 0 0 * * *
  push:
  workflow_dispatch:
env:
  PROFILE: /tmp/.benchmarksprofile

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Because gh actions includes node by default :(
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install bun
        uses: xhyrom/setup-bun@v0.1.3
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        # Use npm because bun doesn't support install field
        run: bun install && cd scripts/tools/paperdave-logger && bun install

      - name: Run setup
        run: |
          bun run setup:init
          bun run setup:languages GITHUB_ACTIONS
          source $PROFILE
          bun run setup:benchmarks

      - name: Run benchmarks
        run: |
          source $PROFILE
          bun run bench

      - name: Generate README
        run: bun run generate

      - name: Set timestamp
        run: echo "timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: branch

      - name: Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: ${{ steps.branch.outputs.branch }}
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          author_name: github-actions[bot]
          message: Update benchmarks ${{ env.timestamp }} 🚀
