name: Run benchmarks

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install bun
        uses: xhyrom/setup-bun@v0.1.3
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Check if installed
        run: |
          bun -v
          node -v
          deno --version

      - name: Setup github-actions account
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          bun install
          for dir in 3rd-packages/*/ ; do
              dir=${dir%*/}
              dir="${dir##*/}"
              
              cd 3rd-packages/$dir
              bun install
              cd ../..
          done
      
      - name: Run benchmarks
        run: bun run bench

      - name: Generate README
        run: bun run generate:readme