name: Run benchmarks

on:
  schedule:
    - cron: 0 0 * * *
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install bun
        uses: xhyrom/setup-bun@v0.1.3
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Run setup
        run: PROFILE=$GITHUB_PATH bun run setup

      - run: deno && $HOME/.deno/bin/deno && cat $GITHUB_PATH

      - name: Run benchmarks
        run: bun run bench

      - name: Generate README
        run: bun run generate

      - name: Set timestamp
        run: echo "timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: branch

      - name: Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: ${{ steps.branch.outputs.branch }}
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          author_name: github-actions[bot]
          message: Update benchmarks ${{ env.timestamp }} 🚀
