name: Run benchmarks

on:
  schedule:
    - cron: 0 0 * * *
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install bun
        uses: xhyrom/setup-bun@v0.1.3
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Check if installed
        run: |
          bun -v
          node -v
          deno --version

      - name: Install dependencies
        run: |
          bun install
          for dir in benchmarks/3rd-packages/*/ ; do
              dir=${dir%*/}
              dir="${dir##*/}"
              
              cd benchmarks/3rd-packages/$dir
              bun install
              cd ../../
          done
      
      - name: Run benchmarks
        run: bun run bench

      - name: Generate README
        run: bun run generate:readme

      - name: Set timestamp
        run: echo "timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Push changes
        uses: actions-js/push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          author_name: github-actions[bot]
          message: Update benchmarks ${{ env.timestamp }} 🚀
